apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: saga-shipping
  labels:
    app: tracking-service
spec:
  type: ClusterIP
  selector:
    app: tracking-service
  ports:
  - name: http
    protocol: TCP
    port: 5009
    targetPort: 5009